/* Reads the desktop app's release manifest so the version, size and date on
   /local are never hardcoded. electron-builder rewrites latest-mac.yml on every
   publish, so the page follows a release without anyone editing this repo.

   The file is public on R2 and tiny. It is fetched with a revalidate window
   rather than at build time, so shipping a new .dmg does not require a site
   deploy to show up. */

const R2_BASE = "https://pub-061018a047d54079b309fb16a26a1ce0.r2.dev/";
const MANIFEST_URL = `${R2_BASE}latest-mac.yml`;

/* The stable route 302s to the newest build and never changes between
   releases, which is what we want on the button long-term.

   It is NOT live yet: today it answers 307 to /applogin, so anyone clicking
   Download would land on a login screen. Until that route ships to production,
   the button uses the direct file URL from the manifest. Flip this to true
   once https://app.construction.live/desktop/download resolves to the .dmg. */
const USE_STABLE_ROUTE = false;
const STABLE_DOWNLOAD_URL = "https://app.construction.live/desktop/download";

/* Used only if the manifest cannot be read, so the button always points at a
   real file rather than disappearing. Safe to fall behind — the app
   self-updates once installed. */
const FALLBACK_DMG = `${R2_BASE}construction.live-0.1.0-arm64.dmg`;

export interface Release {
	version: string;
	/** ISO timestamp, or null if the manifest omitted it. */
	releaseDate: string | null;
	/** Bytes, from the manifest. */
	sizeBytes: number | null;
	downloadUrl: string;
}

/* Hand-rolled rather than pulling in a YAML dependency: the manifest is a
   handful of scalars and one list, generated by a tool with a fixed shape.
   A parser this small is easier to reason about than the failure modes of a
   general one on a file we do not control. */
function parseManifest(text: string) {
	const scalar = (key: string) => {
		const match = text.match(new RegExp(`^${key}:\\s*'?([^'\\n\\r]+?)'?\\s*$`, "m"));
		return match ? match[1] : null;
	};

	/* files:
	     - url: construction.live-0.1.0-arm64.dmg
	       sha512: ...
	       size: 629449658
	   Walked line by line so a `size:` belonging to the top level can never be
	   attached to the last file entry. */
	const files: { url: string; size: number | null }[] = [];
	let inFiles = false;
	let current: { url: string; size: number | null } | null = null;

	for (const rawLine of text.split(/\r?\n/)) {
		if (/^files:\s*$/.test(rawLine)) {
			inFiles = true;
			continue;
		}
		if (inFiles && /^\S/.test(rawLine)) {
			/* Back at column zero, so the list is over. */
			if (current) files.push(current);
			current = null;
			inFiles = false;
			continue;
		}
		if (!inFiles) continue;

		const urlMatch = rawLine.match(/^\s*-\s*url:\s*(\S+)\s*$/);
		if (urlMatch) {
			if (current) files.push(current);
			current = { url: urlMatch[1], size: null };
			continue;
		}
		const sizeMatch = rawLine.match(/^\s*size:\s*(\d+)\s*$/);
		if (sizeMatch && current) current.size = Number(sizeMatch[1]);
	}
	if (current) files.push(current);

	return { version: scalar("version"), releaseDate: scalar("releaseDate"), files };
}

export async function getRelease(): Promise<Release | null> {
	try {
		const response = await fetch(MANIFEST_URL, {
			/* Ten minutes: long enough that the page is not hammering R2, short
			   enough that a release is visible on the site the same morning. */
			next: { revalidate: 600 },
		});
		if (!response.ok) throw new Error(`manifest ${response.status}`);

		const { version, releaseDate, files } = parseManifest(await response.text());
		if (!version) throw new Error("manifest had no version");

		/* The manifest lists the .zip the auto-updater uses as well as the .dmg
		   people download. We want the .dmg. */
		const dmg = files.find((file) => file.url.endsWith(".dmg"));

		return {
			version,
			releaseDate,
			sizeBytes: dmg?.size ?? null,
			downloadUrl: USE_STABLE_ROUTE
				? STABLE_DOWNLOAD_URL
				: dmg
					? `${R2_BASE}${dmg.url}`
					: FALLBACK_DMG,
		};
	} catch (error) {
		/* A download button is the whole point of the page, so an unreachable
		   manifest degrades to a working link without the version line rather
		   than taking the page down. */
		console.error("/local: could not read the release manifest", error);
		return null;
	}
}

/** "629 MB", in the decimal megabytes every download page and OS reports. */
export function formatSize(bytes: number | null) {
	if (!bytes) return null;
	return `${Math.round(bytes / 1e6)} MB`;
}

/** Fixed locale so the server-rendered string can't drift by deploy region. */
export function formatReleaseDate(iso: string | null) {
	if (!iso) return null;
	const date = new Date(iso);
	if (Number.isNaN(date.getTime())) return null;
	return new Intl.DateTimeFormat("en-GB", {
		day: "numeric",
		month: "short",
		year: "numeric",
		timeZone: "UTC",
	}).format(date);
}

export const FALLBACK_DOWNLOAD_URL = FALLBACK_DMG;
